# Continuous Integration & Deployment Pipeline

name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - 'release/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infra/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # ============================================================================
  # Code Quality Checks
  # ============================================================================
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python linters
        run: |
          pip install ruff black mypy

      - name: Run Ruff (Python linter)
        run: ruff check src/ tests/

      - name: Run Black (Python formatter check)
        run: black --check src/ tests/

      - name: Run mypy (Type checking)
        run: mypy src/decision-engine/ --ignore-missing-imports

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js linters
        run: |
          cd src/ui
          npm ci

      - name: Run ESLint
        run: |
          cd src/ui
          npm run lint

      - name: Run Prettier check
        run: |
          cd src/ui
          npm run format:check

  # ============================================================================
  # Bicep Validation
  # ============================================================================
  validate-bicep:
    name: Validate Bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az bicep install
            az bicep version

      - name: Lint Bicep files
        run: |
          find infra -name "*.bicep" -exec az bicep lint --file {} \;

      - name: Build Bicep (validate syntax)
        run: |
          az bicep build --file infra/main.bicep --outdir ./infra/compiled

      - name: Validate ARM template
        run: |
          az deployment sub validate \
            --location eastus2 \
            --template-file infra/compiled/main.json \
            --parameters infra/environments/dev.parameters.json \
            --parameters environmentName=ci-validation

  # ============================================================================
  # Unit Tests
  # ============================================================================
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r src/decision-engine/requirements.txt

      - name: Run unit tests with coverage
        run: |
          pytest tests/unit/ \
            -v \
            --tb=short \
            --cov=src \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=tests/reports/junit.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            tests/reports/
            htmlcov/

  # ============================================================================
  # Build UI
  # ============================================================================
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: src/ui/package-lock.json

      - name: Install dependencies
        run: |
          cd src/ui
          npm ci

      - name: Build
        run: |
          cd src/ui
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: src/ui/dist/

  # ============================================================================
  # Build Decision Engine
  # ============================================================================
  build-decision-engine:
    name: Build Decision Engine
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/decision-engine
          file: ./src/decision-engine/Dockerfile
          push: false
          tags: decision-engine:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================================
  # Contract Tests
  # ============================================================================
  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jsonschema pyyaml

      - name: Validate agent contracts
        run: |
          python tests/contracts/validate_contracts.py

  # ============================================================================
  # Security Scan
  # ============================================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

      - name: Run Checkov (IaC security)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/
          framework: bicep
          soft_fail: true